######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 24 10:19:53 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ut.h
FORMS += ut.ui
SOURCES += tests_generator.cpp ut.cpp
