######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 31 18:17:37 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ut.h
FORMS += ut.ui
SOURCES += tests_generator.cpp ut.cpp
